# Generated by Django 2.0.6 on 2020-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='博文id')),
                ('article_title', models.CharField(max_length=200, verbose_name='博文标题')),
                ('article_content', tinymce.models.HTMLField(blank=True, verbose_name='博文内容')),
                ('article_views', models.BigIntegerField(verbose_name='浏览量')),
                ('article_comment_count', models.BigIntegerField(verbose_name='评论总数')),
                ('article_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('article_like_count', models.CharField(max_length=40, verbose_name='点赞数')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '博文表',
                'verbose_name_plural': '博文表',
                'db_table': 'kxj_articles',
            },
        ),
    ]
