# Generated by Django 2.2 on 2020-07-19 08:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='博文id')),
                ('article_title', models.CharField(max_length=200, verbose_name='博文标题')),
                ('article_introduce', models.CharField(max_length=200, null=True, verbose_name='博文简介')),
                ('article_content', tinymce.models.HTMLField(blank=True, verbose_name='博文内容')),
                ('article_views', models.BigIntegerField(default=0, null=True, verbose_name='浏览量')),
                ('article_comment_count', models.BigIntegerField(default=0, null=True, verbose_name='评论总数')),
                ('article_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间')),
                ('article_like_count', models.BigIntegerField(default=0, null=True, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '博文表',
                'verbose_name_plural': '博文表',
                'db_table': 'kxj_articles',
            },
        ),
    ]
