# Generated by Django 2.0.6 on 2020-07-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
    ]
