# Generated by Django 2.0.6 on 2020-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200716_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_comment_count',
            field=models.BigIntegerField(default=0, null=True, verbose_name='评论总数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.CharField(default='0', max_length=40, null=True, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_views',
            field=models.BigIntegerField(default=0, null=True, verbose_name='浏览量'),
        ),
    ]
