# Generated by Django 2.0.6 on 2020-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200717_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_introduce',
            field=models.CharField(max_length=200, null=True, verbose_name='博文简介'),
        ),
    ]
