# Generated by Django 2.0.6 on 2020-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_article_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_like_count',
            field=models.BigIntegerField(default=0, null=True, verbose_name='点赞数'),
        ),
    ]
