# Generated by Django 2.0.6 on 2020-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles', verbose_name='博文id')),
            ],
            options={
                'verbose_name': '博文设置分类表',
                'verbose_name_plural': '博文设置分类表',
                'db_table': 'kxj_article_sort',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('sort_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类id')),
                ('sort_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('sort_description', models.CharField(max_length=50, verbose_name='分类描述')),
                ('parent_sort_id', models.BigIntegerField(verbose_name='父分类id')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'kxj_sort',
            },
        ),
        migrations.AddField(
            model_name='article_sort',
            name='sort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort.Sort', verbose_name='分类id'),
        ),
    ]
