# Generated by Django 2.0.6 on 2020-07-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_sort',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='article_sort',
            old_name='sort_id',
            new_name='sort',
        ),
    ]
