# Generated by Django 2.0.6 on 2020-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0002_auto_20200716_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='parent_sort_id',
            field=models.BigIntegerField(null=True, verbose_name='父分类id'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='sort_description',
            field=models.CharField(max_length=50, null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='sort_name',
            field=models.CharField(max_length=50, null=True, verbose_name='分类名称'),
        ),
    ]
