# Generated by Django 2.0.6 on 2020-07-17 05:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200716_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_like_count',
            field=models.BigIntegerField(null=True, verbose_name='评论点赞数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment_id',
            field=models.BigIntegerField(null=True, verbose_name='父评论id'),
        ),
    ]
