# Generated by Django 2.0.6 on 2020-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles', verbose_name='博文id')),
            ],
            options={
                'verbose_name': '博文设置标签表',
                'verbose_name_plural': '博文设置标签表',
                'db_table': 'kxj_article_label',
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签表id')),
                ('label_name', models.CharField(max_length=20, verbose_name='标签名称')),
                ('label_alias', models.CharField(max_length=20, verbose_name='标签别名')),
                ('label_description', models.CharField(max_length=50, verbose_name='标签描述')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'kxj_labels',
            },
        ),
        migrations.AddField(
            model_name='article_label',
            name='label_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.Labels', verbose_name='标签id'),
        ),
    ]
