# Generated by Django 2.0.6 on 2020-07-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_label',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='article_label',
            old_name='label_id',
            new_name='label',
        ),
    ]
