# Generated by Django 2.0.6 on 2020-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20200716_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='label_alias',
            field=models.CharField(max_length=20, null=True, verbose_name='标签别名'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='label_description',
            field=models.CharField(max_length=50, null=True, verbose_name='标签描述'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='label_name',
            field=models.CharField(max_length=20, null=True, verbose_name='标签名称'),
        ),
    ]
