# Generated by Django 2.0.6 on 2020-07-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.SmallIntegerField(null=True, verbose_name='用户年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birthday',
            field=models.CharField(max_length=20, null=True, verbose_name='用户生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ip',
            field=models.CharField(max_length=20, null=True, verbose_name='用户ip'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_photo',
            field=models.ImageField(null=True, upload_to='user_head', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_registration_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_telephone_number',
            field=models.ImageField(max_length=11, null=True, upload_to='', verbose_name='用户手机号'),
        ),
    ]
